###############################################################################
# Author: Ozan Aygun
# Date: 06/23/2016
# 
# Similar to summaryppc.R, This function is designed to extract some of the 
# useful summary information from the typical protein-protein-centric summary 
# table generated by spectrum mill
# Conditionally removes human keratins (keratins = TRUE)
# In addition, this tool prepares filtered version of the ppc tables,  
# filtering based on 2 unique peptides and 2 ratio counts 
# Applicable to TMT10 experiment complete summary reports reports
#
# ps=name of the protein centric summary table to be analyzed (char)
# 
# Update 01/30/2017: extending the species choice to Mouse and Human (species = c("HUMAN","MOUSE"))
# The function removes non-human (or non-mouse) contaminants (HUMAN is default species)
#
# Functional, last update on 01/30/2017
################################################################################
summaryppc_filter<-function(ps, keratins=F, species = "HUMAN"){ #ps is the name of the TMT10 protein centric summary table analyzed 
  
      ppc1<-read.csv2(ps,header=TRUE) #read the entire summary table
      ppc2<-read.csv2(ps,header=TRUE, check.names = F) #Same table but directory names in the columns are intact
      
      sp <- toupper(species)
      
      w<-which(ppc1$species!=sp) #Looking for non-human/non-mouse contaminants
      
      ppc1<-ppc1[-w,] #Removes non-human/non-mouse contaminants
      ppc2<-ppc2[-w,] #Removes non-human/non-mouse contaminants
      
      
                      if(keratins == T) {
                        KRT<-read.csv("human_keratins_as_downloaded_from_HGNC_06242016.csv",header =T)
                        KRT<-KRT$Approved
                        
                        w<-which(ppc1$geneSymbol %in%  KRT)
                        
                        
                        if(length(w)>0)  {
                                          ppc1<-ppc1[-w,] #Removes human keratins
                                          ppc2<-ppc2[-w,] #Removes human keratins 
                        }
                      } 
      
      
      
      
      dd<-as.character(colnames(ppc1)[2]) #
      g <- regexpr("\\.[^\\.]*$", dd) # find the position of last dot
      d<-substr(dd,1,g-1) #Name of the general data directory
      
      UP<-which(colnames(ppc1)==paste(d,"unique_peptides",sep=".")) #Position of the unique peptide column
      In1<-which(colnames(ppc1)==paste(d,"TMT_126_total",sep=".")) #The first intensity column
      InL<-which(colnames(ppc1)==paste(d,"TMT_131_total",sep=".")) #The last intensity column
      
      
          num_up<-sum(ppc1[,UP]) # total number of unique peptides identified
  
          num_pro<-length(ppc1[,"subgroupNum"]) #total number of unique proteins
          
          fqppc1<-ppc1[,In1:InL] # only intensity columns of ppc1UP2
            
              m<-which(apply(is.na(fqppc1),1,sum)>0) #Finding the rows that contain at least one missing data (NA)
              
              num_pro_fq<-num_pro-length(m) #total number of proteins fully quantified by all 10 TMT channelS
          
          
      w<-which(ppc1[,UP]>1) #Rows of proteins with at least 2 unique peptides
  
      ppc1UP2<-ppc1[w,] # summary of proteins in ppc with at least 2 unique peptides
  
          num_pro_UP2<-length(ppc1UP2[,"subgroupNum"]) #total number of proteins with at least 2 unique peptides
  
      fqppc1UP2<-ppc1UP2[,In1:InL] # only intensity columns of ppc1UP2
  
          m<-which(apply(is.na(fqppc1UP2),1,sum)>0) #Finding the rows that contain at least one missing data (NA)
  
          num_pro_UP2fq<-num_pro_UP2-length(m) #total number of proteins with at least 2 unique peptides and fully quantified by all 10 TMT channels
  
          
          ##############################################
          fqppc1UP2<-ppc1UP2
          
    if(num_pro_UP2fq != num_pro_UP2){fqppc1UP2<-ppc1UP2[-m,]}   #summary of proteins in ppc with at least 2 unique peptides and fully quantified by all 10 TMT channels
          
          
          
          m<-which(substr(colnames(ppc1),1,18)== "log2_TMT_numRatios") # Find the ratio count columns
          
          RC<-fqppc1UP2[,m]        
          
          u<-(RC[1:nrow(RC),]<2) # a logical data frame that demonstrates which ratio counts are smaller than 2
          
          w<-which(apply(u,1,sum)>0) #Finding the rows that contain proteins less than 2 ratio counts
          
         num_pro_UP2fq_RC2<-num_pro_UP2fq-length(w) #total number of proteins with at least 2 unique peptides and fully quantified by all 10 TMT channels and at least 2 ratio counts
          
  reportps<-data.frame(num_up,num_pro,num_pro_fq,num_pro_UP2,num_pro_UP2fq,num_pro_UP2fq_RC2)
  
  colnames(reportps)<-c("number of unique peptides",
                        "number of unique proteins",
                        "number of fully quantified proteins",
                        "number of proteins with at least 2 unique peptides", 
                        "number of proteins with at least 2 unique peptides and fully quantified",
                        "number of proteins with at least 2 unique peptides,fully quantified with at least 2 Ratio Counts")
 
  finalreport<- t(reportps) # transposed version of the data table
  
  colnames(finalreport)[1]<-paste(getwd(),ps,sep="/")
  
  print(finalreport)
  
  write.csv(file=paste("summaryppc",substr(ps,1,nchar(ps)-4),".csv",sep="_"),finalreport) #printing the final report as a csv file
  
  ###############################################################################################################################################
  
  # Filtering ppc2 and preparing the filtered reports
  
  
  w<-which((ppc2[,UP]>1) & (apply(is.na(ppc2[,In1:InL]),1,sum)== 0 ) ) #Rows of proteins with at least 2 unique peptides and fully quantified
  
  ppc2UP2fq<-ppc2[w,] # summary of proteins in ppc with at least 2 unique peptides and fully quantified
  
  write.csv2(file =paste(substr(ps,1,nchar(ps)-4),"UP2_FQ",".ssv",sep="_"),ppc2UP2fq,row.names = F )# Writes the ssv report of the UP2 and FQ filtered ppc 
  
  
  m<-which(substr(colnames(ppc2),1,18)== "log2_TMT_numRatios") # Find the ratio count columns
  
  RC<-ppc2[,m]        
  
  u<-(RC[1:nrow(RC),]<2) # a logical data frame that demonstrates which ratio counts are smaller than 2
  

  
  w<-which((ppc2[,UP]>1) & (apply(is.na(ppc2[,In1:InL]),1,sum)== 0 ) & (apply(u,1,sum) == 0 )  ) #Rows of proteins with at least 2 unique peptides and fully quantified with at least 2 ratio counts
  
  ppc2UP2fqRC2<-ppc2[w,] # summary of proteins in ppc with at least 2 unique peptides and fully quantified with at least 2 ratio counts

  write.csv2(file =paste(substr(ps,1,nchar(ps)-4),"UP2_FQ_RC2",".ssv",sep="_"),ppc2UP2fqRC2,row.names = F )# Writes the ssv report of the UP2 and FQ filtered ppc 
  
  }